### ISSUE TITLE
[Feature] Investment Tracking

### ISSUE THREAD

**Issue by namsnath** [namsnath/money_manager#2]
# [Feature] Investment Tracking

## Motivation
- Replace the generic spreadsheet to track investments

### Database Design
- [ ] Add a `TransactionType` for `Investment`
- [ ] Add a `TransactionType` for `InvestmentReturn`
- [ ] Make an `Investments` table
  - [ ] FK to a transaction, `transaction` stores usual details, `investment` stores specific data
  - [ ] Add `Categories` like Equity, FD, etc.
  - [ ] Specific data: Rate, time-period, maturity date, current value
- [ ] OR Make separate tables for different investment types (`Equity`, `FD`, etc.)

### UI/UX
- [ ] Separate page from Income/Expense/Transfer
- [ ] Separate section for summary
- [ ] Show notification when maturity reached, click to do a `InvestmentReturn` transaction
- [ ] Add page to track equity/MFs/etc.
- [ ] Show performance of each investment
- [ ] Show `CategoryChart` for Investments to show breakup
  - [ ] Show `InvestmentCategoryChart (?)` to show stocks instead of categories (Like 5% Spicejet, 2% Gold)

### Other
- [ ] Allow choosing manual/automatic updates for current value
- [ ] Update current value from Google Finance (?) periodically
